# Generated by Django 4.1.4 on 2023-07-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_column='user_email', max_length=256, null=True),
        ),
    ]
